import { api } from './client'
import type { Area, Crop, Cultivation, Field, Harvest, PagedResponse, Photo, WorkLog } from '../types'
const page = <T>(path: string) => api.get<PagedResponse<T>>(path)
export const fields = { list: () => page<Field>('/fields'), get: (id: string) => api.get<Field>(`/fields/${id}`), create: (v: unknown) => api.post<Field>('/fields', v), update: (id: string, v: unknown) => api.put<Field>(`/fields/${id}`, v), delete: (id: string) => api.delete(`/fields/${id}`) }
export const areas = { list: (fieldId: string) => page<Area>(`/fields/${fieldId}/areas`), get: (fieldId: string, id: string) => api.get<Area>(`/fields/${fieldId}/areas/${id}`), create: (fieldId: string, v: unknown) => api.post<Area>(`/fields/${fieldId}/areas`, v), update: (fieldId: string, id: string, v: unknown) => api.put<Area>(`/fields/${fieldId}/areas/${id}`, v), delete: (fieldId: string, id: string) => api.delete(`/fields/${fieldId}/areas/${id}`), cultivations: (fieldId: string, id: string) => page<Cultivation>(`/fields/${fieldId}/areas/${id}/cultivations`) }
export const crops = { list: () => page<Crop>('/crops'), get: (id: string) => api.get<Crop>(`/crops/${id}`), create: (v: unknown) => api.post<Crop>('/crops', v), update: (id: string, v: unknown) => api.put<Crop>(`/crops/${id}`, v) }
export const cultivations = { list: () => page<Cultivation>('/cultivations'), current: () => page<Cultivation>('/cultivations/current'), get: (id: string) => api.get<Cultivation>(`/cultivations/${id}`), create: (v: unknown) => api.post<Cultivation>('/cultivations', v), update: (id: string, v: unknown) => api.put<Cultivation>(`/cultivations/${id}`, v), delete: (id: string) => api.delete(`/cultivations/${id}`) }
export const workLogs = { list: (id: string) => page<WorkLog>(`/cultivations/${id}/work-logs`), get: (id: string, child: string) => api.get<WorkLog>(`/cultivations/${id}/work-logs/${child}`), create: (id: string, v: unknown) => api.post<WorkLog>(`/cultivations/${id}/work-logs`, v), update: (id: string, child: string, v: unknown) => api.put<WorkLog>(`/cultivations/${id}/work-logs/${child}`, v), delete: (id: string, child: string) => api.delete(`/cultivations/${id}/work-logs/${child}`) }
export const harvests = { list: (id: string) => page<Harvest>(`/cultivations/${id}/harvests`), get: (id: string, child: string) => api.get<Harvest>(`/cultivations/${id}/harvests/${child}`), create: (id: string, v: unknown) => api.post<Harvest>(`/cultivations/${id}/harvests`, v), update: (id: string, child: string, v: unknown) => api.put<Harvest>(`/cultivations/${id}/harvests/${child}`, v), delete: (id: string, child: string) => api.delete(`/cultivations/${id}/harvests/${child}`) }
export const photos = { list: (id: string) => page<Photo>(`/cultivations/${id}/photos`), upload: (id: string, v: FormData) => api.post<Photo>(`/cultivations/${id}/photos`, v), delete: (id: string, child: string) => api.delete(`/cultivations/${id}/photos/${child}`) }
